name: Godot Export

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Godot
      run: |
        wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
        unzip Godot_v4.3-stable_linux.x86_64.zip -d godot
        chmod +x godot/Godot_v4.3-stable_linux.x86_64

    - name: Prepare export directories
      run: |
        mkdir -p ${{ github.workspace }}/.godot/editor
        chmod -R 777 ${{ github.workspace }}/.godot/editor  # Ensure write permissions

    - name: Export Project with Godot
      run: |
        ./godot/Godot_v4.3-stable_linux.x86_64 --headless \
        --path ${{ github.workspace }} \
        --export-debug "Linux" ${{ github.workspace }}/MyGame.x86_64  # Adjust preset and path

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyGame
        path: ${{ github.workspace }}/MyGame.x86_64
