name: Godot Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Use Docker container with Godot pre-installed
      - name: Run Godot Headless in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace barichello/godot-ci:4.3 \
          /usr/local/bin/godot --headless --path /workspace --export-debug "Linux/X11" /workspace/build/MyGame.x86_64

      # Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyGame.x86_64
          path: build/MyGame.x86_64
