name: Godot Build & Export

on:
  push:
    branches:
      - main  # Trigger on push to main
  pull_request:
    branches:
      - main  # Trigger on PR to main

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out the repo to the runner

      - name: Set up Godot Headless
        run: |
          sudo add-apt-repository ppa:godotengine/ppa -y
          sudo apt-get update
          sudo apt-get install -y godot3-headless  # Install Godot headless version

      - name: Download Export Templates
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates
          tar -xvf Godot_v4.3-stable_export_templates.tpz -C ~/.local/share/godot/export_templates

      - name: Run Export
        run: godot --headless --path . --export-debug "Linux" ./build/MyGame.x86_64  # Export for Linux

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3  # Upload the exported build as an artifact
        with:
          name: linux-build
          path: ./build/MyGame.x86_64
