name: Godot Build & Export

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch.
  pull_request:
    branches:
      - main  # Also trigger on pull requests to the main branch.

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Clone the repository into the runner.

      - name: Cache Godot Editor Files
        uses: actions/cache@v2
        with:
          path: ~/.cache/godot  # Cache Godot files for faster builds.
          key: ${{ runner.os }}-godot-cache  # Use OS as part of the cache key.

      - name: Set up Godot Headless
        run: sudo apt-get update && sudo apt-get install -y godot-headless  # Install the headless version of Godot.

      - name: Run Unit Tests
        run: godot --path . --headless --run-tests  # Execute tests in headless mode before building.

      - name: Build Linux Project
        run: godot --path . --headless --export-debug "Linux/X11" ./build/MyGame.x86_64  # Export Linux build.

      - name: Build Windows Project
        run: godot --path . --headless --export-debug "Windows Desktop" ./build/MyGame.exe  # Export Windows build.

      - name: Build HTML5 Project
        run: godot --path . --headless --export-debug "HTML5" ./build/MyGame.html  # Export HTML5 build.

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: game-builds  # Name for the uploaded artifacts.
          path: |  # Specify paths to the exported builds.
            ./build/MyGame.x86_64
            ./build/MyGame.exe
            ./build/MyGame.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Deploy the
