name: Godot Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Godot Headless
      - name: Download Godot Headless
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux_headless.64.zip
          unzip Godot_v4.3-stable_linux_headless.64.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/Godot_v4.3-stable_linux_headless.64

      # Export project using Godot headless
      - name: Export Project with Godot
        run: |
          /usr/local/bin/Godot_v4.3-stable_linux_headless.64 --headless --path /github/workspace --export-debug "Linux/X11" /github/workspace/build/MyGame.x86_64

      # Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyGame.x86_64
          path: /github/workspace/build/MyGame.x86_64
