name: Build Godot Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Godot Standard
        run: wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip

      - name: Extract Godot
        run: unzip Godot_v4.3-stable_linux.x86_64.zip

      - name: Run Godot in Headless Mode
        run: ./Godot_v4.3-stable_linux.x86_64/godot --headless --export-debug "Linux" /path/to/output/file

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: exported-project
          path: /path/to/output/file
