name: Godot Build & Export

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Godot Docker image
        run: docker pull barichello/godot-ci:4.3

      - name: Build Project with Docker
        run: |
          docker run --rm \
            --workdir /godot/project \
            --volume $(pwd):/godot/project \
            barichello/godot-ci:4.3 \
            /usr/local/bin/godot --headless --path /godot/project --export-debug "Linux/X11" /godot/project/MyGame.x86_64

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: ./MyGame.x86_64
