name: Simple Godot Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Godot Headless (Standard)
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux_server.64.zip
          unzip Godot_v4.3-stable_linux_server.64.zip -d godot

      - name: Export Project with Godot
        run: |
          ./godot/godot_server.64 --headless --path /workspace/ --export-debug "Linux" MyGame.x86_64

      - name: Upload build artifact
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: exported-project
          path: MyGame.x86_64
