name: Godot Export

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Godot
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux_server.64.zip
        unzip Godot_v4.3-stable_linux_server.64.zip -d godot
        chmod +x godot/Godot_v4.3-stable_linux_server.64

    - name: Export Project with Godot
      run: |
        ./godot/Godot_v4.3-stable_linux_server.64 --headless --path /home/runner/work/dynamic-world-changer/dynamic-world-changer --export-debug "Linux/X11" /home/runner/work/dynamic-world-changer/dynamic-world-changer/MyGame.x86_64

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyGame
        path: /home/runner/work/dynamic-world-changer/dynamic-world-changer/MyGame.x86_64
