name: Godot Export

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Removed the Godot Headless download section

    - name: Export Project with Godot
      run: |
        /path/to/your/godot_executable --headless --path /home/runner/work/dynamic-world-changer/dynamic-world-changer --export-debug "Linux/X11" /home/runner/work/dynamic-world-changer/dynamic-world-changer/MyGame.x86_64

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyGame
        path: /home/runner/work/dynamic-world-changer/dynamic-world-changer/MyGame.x86_64
