name: Godot Build & Export

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Download Godot Headless binary
      - name: Download Godot Headless
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux_server.64.zip
          unzip Godot_v4.3-stable_linux_server.64.zip -d godot-headless
          chmod +x godot-headless/Godot_v4.3-stable_linux_server.64

      # Step 3: Download Export Templates
      - name: Download export templates
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates
          tar -xvf Godot_v4.3-stable_export_templates.tpz -C ~/.local/share/godot/export_templates

      # Step 4: Build the project
      - name: Export project
        run: ./godot-headless/Godot_v4.3-stable_linux_server.64 --headless --path . --export-debug "Linux" ./build/MyGame.x86_64

      # Step 5: Upload the exported build as an artifact (v3)
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: ./build/MyGame.x86_64
