name: Godot Build & Export

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Godot Headless with Docker
        run: |
          docker pull barichello/godot-ci:4.3
          docker run --rm -v $PWD:/godot --user $(id -u):$(id -g) -w /godot barichello/godot-ci:4.3 /godot --headless --path /godot --export-debug "Linux" /godot/build/MyGame.x86_64

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: ./build/MyGame.x86_64
