name: Godot Build & Export

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker and use the Godot Headless Docker image
      - name: Set up Godot Headless with Docker
        run: |
          docker pull barichello/godot-ci:4.3
          docker run --rm -v $PWD:/godot barichello/godot-ci:4.3 /godot --headless --path /godot --export-debug "Linux" /godot/build/MyGame.x86_64

      # Step 3: Upload the exported build as an artifact (updated to v3)
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: ./build/MyGame.x86_64
