name: Godot Export for macOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner instead of Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Godot for macOS
      run: |
        wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_macos.universal.zip
        unzip Godot_v4.3-stable_macos.universal.zip -d godot
        chmod +x godot/Godot_v4.3-stable_macos.universal

    - name: Export Project with Godot
      run: |
        ./godot/Godot_v4.3-stable_macos.universal --headless \
        --path ${{ github.workspace }} \
        --export-debug "Mac OSX" ${{ github.workspace }}/MyGame.app

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyGame
        path: ${{ github.workspace }}/MyGame.app
