name: Godot Build & Export

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # No changes needed here.

      - name: Cache Godot Editor Files
        uses: actions/cache@v2
        with:
          path: ~/.cache/godot
          key: ${{ runner.os }}-godot-cache

      - name: Set up Godot Headless
        run: sudo apt-get update && sudo apt-get install -y godot-headless

      - name: Build Linux Project
        run: godot --path . --headless --export-debug "Linux/X11" ./build/MyGame.x86_64

      - name: Build Windows Project
        run: godot --path . --headless --export-debug "Windows Desktop" ./build/MyGame.exe

      - name: Build HTML5 Project
        run: godot --path . --headless --export-debug "HTML5" ./build/MyGame.html

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: game-builds
          path: |
            ./build/MyGame.x86_64
            ./build/MyGame.exe
            ./
